### ISSUE TITLE
Feature: The media UI should obey editorOptions type constraints

### ISSUE THREAD

**Issue by klfman** [Flowpack/media-ui#14]
This description refers to the old media UI. I would like the behavior to change with this rewrite.

# Behavior in the old media UI

When I impose restrictions on a nodetype property of type ImageInterface like this:

```yaml
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        inspector:
          editorOptions:
            accept: 'image/jpeg'
```

The upload modal will restrict the editors to uploading jpegs but they can still choose any other format directly from the media library.

# How it should work
The media UI should obey the editorOptions config and filter the media accordingly, so only the restricted formats can be chosen.
This, however, needs to be clear to the user. Could for example be solved via a mesage or an information popup that their choice is "illegal" if they happen to choose a different format.
