### ISSUE TITLE
Nested structures for organising assets

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/media-ui#64]
It became apparent in many projects that the current tag and collection system doesn't cover all cases in which editors would like to organise their assets.
Other (DAM) systems also use folder like structures that can currently not be synced into Neos.

Often something like folders (similar to TYPO3) are requested.

The initial idea (see #3) was to implement nested tags. But when discussing the idea further more problems with this approach came up so the idea was dropped for now.
As tags can be assigned to any asset and more than one, thinking of them as folders doesn't really work well.

Collections were also meant for something else. As their can be assigned to sites and restricted via policies nesting them would also not solve our issues.

Therefore a new type `Folder` could be introduced that can be nested and could already be implemented in the Neos CR.
This way we could introduce them in parallel via the new Media UI without modifying the old UI or its API. At the same time this would be the first step to move everything into the CR asset related to have also translation and other capabilities in the future that are often requested.
Integrators could access this folder nodetree to already use it to access & reference assets.

A folder should have a label (translateable via the CR) and childnodes, those can be assets or more folders initially.
This can later be extended via NodeTypes.

**Comment by Sebobo** [comment]
@bwaidelich you said during our last call about this topic (last summer?) you wanted to write down an architecture idea. Maybe you can find some time in the next weeks to do this, would be awesome :)

**Comment by DrillSergeant** [comment]
@Sebobo Thanks for those ideas. In almost every Neos project our customers are missing a folder-structure to organize their assets. I also connected meanwhile different DAM-systems which had folder-structures. I am sure this feature would be loved by many customers.

**Comment by tdausner** [comment]
Why don't utilize collections having a nested structure?
Example collections
```
site1/
site1/usergroup1
site1/usergroup1/purpose1
site1/usergroup1/purpose2
site1/usergroup1/purpose2/subset1
site1/usergroup2
site1/usergroup2/purpose1
site1/usergroup2/purpose2
site2/
...
```
(the separation character could be defined in a yaml file)

This nested collection structure could be displayed in a "folder tree"
```
site1
  usergroup1
    purpose1
    purpose2
      subset1
  usergroup2
    purpose1
    purpose2
site2
...
```
To achieve simple site dependent restricted access to the asset collections the `privilegeTargets` matchers are extended (a job I've already done but still under test):
```
privilegeTargets:

  'Neos\Media\Security\Authorization\Privilege\ReadAssetCollectionPrivilege':
    'First.Site:AssetCollection':
      label: 'First site asset collection access'
      matcher: 'titleStartsWith("site1/")'
    'Second.Site:AssetCollection':
      label: 'Second site asset collection access'
      matcher: 'titleStartsWith("site2/")'

  'Neos\Media\Security\Authorization\Privilege\ReadAssetPrivilege':
    'First.Site:AssetRead':
      label: 'First site asset access'
      matcher: 'isInCollectionStartsWith("site1/")'
    'Second.Site:AssetRead':
      label: 'Second site asset access'
      matcher: 'isInCollectionStartsWith("site2/")'
```
with the corresponding roles:
```
roles:
  'First.Site:FirstAssets':
    label: 'First site asset access'
    description: 'Access to First-Assets'
    parentRoles: ['Neos.Neos:Editor']
    privileges:
      -
        privilegeTarget: 'First.Site:AssetCollection'
        permission: GRANT
      -
        privilegeTarget: 'First.Site:AssetRead'
        permission: GRANT

  'Second.Site:SecondAssets':
    label: 'Second site asset access'
    description: 'Access to Second-Assets'
    parentRoles: ['Neos.Neos:Editor']
    privileges:
      -
        privilegeTarget: 'Second.Site:AssetCollection'
        permission: GRANT
      -
        privilegeTarget: 'Second.Site:AssetRead'
        permission: GRANT
```
(don't forget to give administrator & asset manager the same privileges)

IMHO it's always best to reuse proven code as the NEOS `privilegeTarget` system is. NEOS wins a "folder structure" by a backend visualization task (in `gridLeft` and `gridRight`). And the new mechanism of tagging still coincides with such a nested collection nested structure
